services:
  - type: web
    name: sky-shop-release
    runtime: node
    buildCommand: npm install && npm run build && npx playwright install --with-deps chromium
    startCommand: npm run start
    healthCheckPath: /api/market/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
