services:
  - type: web
    name: sky-shop-release
    runtime: node
    buildCommand: npm install && npm run build && PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install chromium
    startCommand: PLAYWRIGHT_BROWSERS_PATH=0 npm run start
    healthCheckPath: /api/market/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
